version: "3.8"
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: productdb
      MYSQL_ROOT_PASSWORD: superdupersecurepassword
      MYSQL_USER: tla
      MYSQL_PASSWORD: supersecurepassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: ProductInformationApi/Dockerfile
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=productdb;User=tla;Password=supersecurepassword;"
    depends_on:
      - mysql

volumes:
  mysql_data:
