// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductInformationApi.Contexts;

#nullable disable

namespace ProductInformationApi.Migrations
{
    [DbContext(typeof(ProductInformationDbContext))]
    [Migration("20250416132711_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("ProductInformationApi.Models.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5309b913-7cb5-48b4-b32d-2188da5ef21a"),
                            Name = "Apple Inc."
                        },
                        new
                        {
                            Id = new Guid("c0db3ed1-80dc-491f-812a-84bdd749ba03"),
                            Name = "Sony Corporation"
                        },
                        new
                        {
                            Id = new Guid("de29706e-27e0-4765-aeea-835cc605b4f3"),
                            Name = "Dell Technologies"
                        });
                });

            modelBuilder.Entity("ProductInformationApi.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f3c2bd3-d55f-4d76-b31c-d49e99d6c721"),
                            ManufacturerId = new Guid("5309b913-7cb5-48b4-b32d-2188da5ef21a"),
                            Name = "iPhone 15 Pro"
                        },
                        new
                        {
                            Id = new Guid("b62b5be6-d52b-4e70-bc3d-20d4a8e3e8dc"),
                            ManufacturerId = new Guid("5309b913-7cb5-48b4-b32d-2188da5ef21a"),
                            Name = "MacBook Air M3"
                        },
                        new
                        {
                            Id = new Guid("e9171371-3aeb-4420-8ba0-91ec3b54193b"),
                            ManufacturerId = new Guid("c0db3ed1-80dc-491f-812a-84bdd749ba03"),
                            Name = "PlayStation 5"
                        },
                        new
                        {
                            Id = new Guid("5c79e189-2e8c-414e-bdf1-d3b3de2bb226"),
                            ManufacturerId = new Guid("c0db3ed1-80dc-491f-812a-84bdd749ba03"),
                            Name = "Sony WH-1000XM5"
                        },
                        new
                        {
                            Id = new Guid("fa3c2285-74f3-4c71-a2d3-3c8b80829ac7"),
                            ManufacturerId = new Guid("de29706e-27e0-4765-aeea-835cc605b4f3"),
                            Name = "XPS 13"
                        },
                        new
                        {
                            Id = new Guid("0d71b234-d672-4e8b-a7f5-13d55cd3b21e"),
                            ManufacturerId = new Guid("de29706e-27e0-4765-aeea-835cc605b4f3"),
                            Name = "Alienware Aurora R13"
                        });
                });

            modelBuilder.Entity("ProductInformationApi.Models.Product", b =>
                {
                    b.HasOne("ProductInformationApi.Models.Manufacturer", null)
                        .WithMany("Products")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductInformationApi.Models.Manufacturer", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
